version: '3.9'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./market
    ports:
      - "3000:3000"
    volumes:
      - ./market:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://127.0.0.1:8000
