version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    environment:
      - API_KEY=your_api_key_here
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./market
    volumes:
      - ./market:/app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://backend:8000
      - NODE_ENV=dev
