/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutBlock: typeof import('./src/components/AboutBlock.vue')['default']
    AnalyticsMarket: typeof import('./src/components/analytics/AnalyticsMarket.vue')['default']
    AnalyticsMarketReview: typeof import('./src/components/analytics/AnalyticsMarketReview.vue')['default']
    AnalyticsPrices: typeof import('./src/components/analytics/AnalyticsPrices.vue')['default']
    BaseAvatar: typeof import('./src/components/base/BaseAvatar.vue')['default']
    BaseBadge: typeof import('./src/components/base/BaseBadge.vue')['default']
    BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
    BaseCard: typeof import('./src/components/base/BaseCard.vue')['default']
    BaseCheckbox: typeof import('./src/components/base/BaseCheckbox.vue')['default']
    BaseCheckboxGroup: typeof import('./src/components/base/BaseCheckboxGroup.vue')['default']
    BaseColorWidget: typeof import('./src/components/base/controls/BaseColorWidget.vue')['default']
    BaseContentEditable: typeof import('./src/components/base/controls/BaseContentEditable.vue')['default']
    BaseForm: typeof import('./src/components/base/BaseForm.vue')['default']
    BaseFormField: typeof import('./src/components/base/BaseFormField.vue')['default']
    BaseFragment: typeof import('./src/components/base/BaseFragment.vue')['default']
    BaseGallery: typeof import('./src/components/base/BaseGallery.vue')['default']
    BaseGalleryLinkable: typeof import('./src/components/base/BaseGalleryLinkable.vue')['default']
    BaseIcon: typeof import('./src/components/base/icon/BaseIcon.vue')['default']
    BaseImageInput: typeof import('./src/components/base/controls/BaseImageInput.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BaseLink: typeof import('./src/components/base/BaseLink.vue')['default']
    BaseLocaleLink: typeof import('./src/components/base/BaseLocaleLink.vue')['default']
    BaseMenu: typeof import('./src/components/base/BaseMenu.vue')['default']
    BaseModal: typeof import('./src/components/base/BaseModal.vue')['default']
    BaseMultiSelect: typeof import('./src/components/base/controls/BaseMultiSelect.vue')['default']
    BaseObserve: typeof import('./src/components/base/BaseObserve.vue')['default']
    BasePullRefresh: typeof import('./src/components/base/pull-refresh/BasePullRefresh.vue')['default']
    BaseRadioGroup: typeof import('./src/components/base/controls/BaseRadioGroup.vue')['default']
    BaseRatio: typeof import('./src/components/base/BaseRatio.vue')['default']
    BaseSearchBox: typeof import('./src/components/base/BaseSearchBox.vue')['default']
    BaseSelect: typeof import('./src/components/base/BaseSelect.vue')['default']
    BaseSelectAsync: typeof import('./src/components/base/controls/BaseSelectAsync.vue')['default']
    BaseSpinner: typeof import('./src/components/base/BaseSpinner.vue')['default']
    BaseTabs: typeof import('./src/components/base/BaseTabs.vue')['default']
    BaseTextarea: typeof import('./src/components/base/controls/BaseTextarea.vue')['default']
    ChatAssistant: typeof import('./src/components/ChatAssistant.vue')['default']
    CompanyReport: typeof import('./src/components/CompanyReport.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    LoginView: typeof import('./src/components/LoginView.vue')['default']
    MarkdownBlock: typeof import('./src/components/MarkdownBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
